djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

# routes
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('about/', views.about),
    path('', article_views.article_list, name='home')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('signup/', views.signup_view, name='signup'),
  path('login/', views.login_view, name='login'),
  path('logout/', views.logout_view, name='logout'),
]

models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
  title = models.CharField(max_length=100)
  slug = models.SlugField()
  body = models.TextField()
  date = models.DateTimeField(auto_now_add=True)
  thumb = models.ImageField(default='default.png', blank=True)
  author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
  # add in thumbnail later
  # add in author later

  def __str__(self):
    return self.title

  def snippet(self):
    return self.body[:50]

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
  class Meta:
    model = models.Article
    fields = ['title', 'body', 'slug', 'thumb']
    

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def about(req):
  # return HttpResponse('about')
  return render(req, 'about.html')

def home(req):
  return render(req, 'homepage.html')

views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(req):
  if req.method == 'POST':
    form = UserCreationForm(req.POST)
    
    if form.is_valid():
      user = form.save()
      login(req, user)
      print('SAVED')
      return redirect('articles:list')
  else:
    form = UserCreationForm()
  return render(req, 'accounts/signup.html', {'form': form})

def login_view(req):
  if req.method == 'POST':
    form = AuthenticationForm(data=req.POST)
    
    if form.is_valid():
      user = form.get_user()
      login(req, user)
      if 'next' in req.POST:
        return redirect(req.POST.get('next'))
      return redirect('articles:list')

  else:
    form = AuthenticationForm()
  return render(req, 'accounts/login.html', {'form': form, 'req': req})

def logout_view(req):
  if req.method == 'POST':
    logout(req)
    return redirect('articles:list')

djangonautic/templates/about.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>About</title>
</head>
<body>
  <h1>This is the About page </h1>
  <p>WE like Django!</p>
</body>
</html>

djangonautic/templates/base_layout.html
{% load static %}

<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'styles.css' %}">
  <title>Articles</title>
</head>

<body>
  <header class="wrapper">
    <h1>
      <a href="{% url 'home' %}"><img src="{% static 'llgo.png' %}" /></a>
    </h1>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li>
          <form class='logout-link' action="{% url 'accounts:logout' %}" method='post'>
            {% csrf_token %}
            <button type="submit">Logout</button>
          </form>
        </li>
        <li>
          <a href="{% url 'articles:create' %}" class="highlight">New Article</a>
        </li>
        {% else %}
        <li>
          <a href="{% url 'accounts:login' %}">Login</a>
        </li>

        <li>
          <a href="{% url 'accounts:signup' %}">Signup</a>
        </li>
        {% endif %}
      </ul>
    </nav>

  </header>
  <div class="wrapper">


    {% block content %}

    {% endblock %}
  </div>
</body>

</html>

djangonautic/templates/homepage.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Homepage</title>
</head>
<body>
  <h1>This is the Homepage </h1>
  <p>Welcome to the first tutorial</p>
</body>
</html>

templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="create-article">
    <h2>Create an Awesome New Article</h2>
    <form action="{% url 'articles:create' %}" class="site-form" method='post' enctype="multipart/form-data">
      {% csrf_token %}
      {{form}}
      <input type="submit" value='Create'>
    </form>
  </div>
  <script src='/static/slugify.js'></script>
{% endblock %}

templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="article-detail">
    <div class="article">
      <img src="{{article.thumb.url}}" alt="{{article.title}}">
      <h2>{{ article.title }} </h2>
      <p>{{ article.body }} </p>
      <p> {{ article.date }} </p>
    </div>
  </div>
{% endblock %}

templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>Article List</h1>
  <div class="articles">
    {% for article in articles %}
    <div class="article">
      <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
      <p>{{article.snippet}} </p>
      <p>{{article.date}}</p>
      <p class="author">added by {{article.author.username}}</p>
    </div>
    {% endfor %}
  </div>
{% endblock %}